name: Tests
on: [push, pull_request]
jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6
      - name: Run Tests
        run: dotnet test -l "console;verbosity=normal"